version: '3.8'

services:
  multas-api-staging:
    container_name: multas-api-staging
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5102:8080"
    networks:
      - network_staging
    labels:
      - com.multas.environment=staging

networks:
  network_staging:
    driver: bridge
