version: '3.8'

services:
  multas-api-staging:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: multas-api-staging
    restart: always
    depends_on:
      - sqlserverBack-staging
    env_file:
      - .env
    ports:
      - "5102:8080"
    networks:
      - multas_network
    labels:
      - com.multas.environment=staging

volumes:
  sqlserver_data_staging:

networks:
  multas_network:
    external: true