version: '3.8'

services:
  sqlserverBack-staging:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverBack-staging
    restart: always
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_PASSWORD}
    ports:
      - "1436:1433"
    volumes:
      - sqlserver_data_staging:/var/opt/mssql
    networks:
      - network_staging

  multas-api-staging:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: multas-api-staging
    restart: always
    depends_on:
      - sqlserverBack-staging
    env_file:
      - .env
    ports:
      - "5102:8080"
    networks:
      - network_staging
    labels:
      - com.multas.environment=staging

volumes:
  sqlserver_data_staging:

networks:
  network_staging:
    driver: bridge
