version: '3.8'

services:
  sqlserverBack-qa:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverBack-qa
    restart: always
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_PASSWORD}
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data_qa:/var/opt/mssql
    networks:
      - network_qa

  multas-api-qa:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: multas-api-qa
    restart: always
    depends_on:
      - sqlserverBack-qa
    env_file:
      - .env
    ports:
      - "5101:8080"
    networks:
      - network_qa
    labels:
      - com.multas.environment=qa

volumes:
  sqlserver_data_qa:

networks:
  network_qa:
    driver: bridge
