version: '3.8'

services:

  multas-api-qa:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: multas-api-qa
    restart: always
    depends_on:
      - sqlserverBack-qa
    env_file:
      - .env
    ports:
      - "5101:8080"
    networks:
      - multas_network
    labels:
      - com.multas.environment=qa

volumes:
  sqlserver_data_qa:

networks:
  multas_network:
    external: true
