version: '3.8'

services:
  multas-api-qa:
    container_name: multas-api-qa
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5101:8080"
    networks:
      - network_qa
    labels:
      - com.multas.environment=qa

networks:
  network_qa:
    driver: bridge
