services:
  multas-api-qa:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: multas-api-qa
    restart: always
    env_file:
      - .env
    ports:
      - "5101:8080"
    networks:
      - multas_network
    labels:
      - com.multas.environment=qa

networks:
  multas_network:
    external: true
