version: '3.8'

services:
  sqlserverBack-prod:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverBack-prod
    restart: always
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_PASSWORD}
    ports:
      - "1437:1433"
    volumes:
      - sqlserver_data_prod:/var/opt/mssql
    networks:
      - network_prod

  multas-api-prod:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: multas-api-prod
    restart: always
    depends_on:
      - sqlserverBack-prod
    env_file:
      - .env
    ports:
      - "5103:8080"
    networks:
      - network_prod
    labels:
      - com.multas.environment=prod

volumes:
  sqlserver_data_prod:

networks:
  network_prod:
    driver: bridge
