version: '3.8'

services:
  multas-api-prod:
    container_name: multas-api-prod
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5103:8080"
    networks:
      - network_prod
    labels:
      - com.multas.environment=prod

networks:
  network_prod:
    driver: bridge
