version: '3.8'

services:
  postgresBack-prod:
    image: postgres:16
    container_name: postgresBack-prod
    restart: always
    env_file:
      - .env
    ports:
      - "5437:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - network_prod

  multas-api-prod:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: multas-api-prod
    restart: always
    depends_on:
      - postgresBack-prod
    env_file:
      - .env
    ports:
      - "5103:8080"
    networks:
      - network_prod
    labels:
      - com.multas.environment=prod

volumes:
  postgres_data_prod:

networks:
  network_prod:
    driver: bridge
