version: '3.8'

services:

  multas-api-prod:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: multas-api-prod
    restart: always
    depends_on:
      - sqlserverBack-prod
    env_file:
      - .env
    ports:
      - "5103:8080"
    networks:
      - multas_network
    labels:
      - com.multas.environment=prod

volumes:
  sqlserver_data_prod:

networks:
  multas_network:
    external: true