version: '3.8'

services:
  sqlserverBack-dev:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverBack-dev
    restart: always
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_PASSWORD}
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data_dev:/var/opt/mssql
    networks:
      - network_dev

  multas-api-dev:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: multas-api-dev
    restart: always
    depends_on:
      - sqlserverBack-dev
    env_file:
      - .env
    ports:
      - "5100:8080"
    networks:
      - network_dev
    labels:
      - com.multas.environment=dev

volumes:
  sqlserver_data_dev:

networks:
  network_dev:
    driver: bridge
