version: '3.8'

services:
  multas-api-dev:
    container_name: multas-api-dev
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5100:8080"
    networks:
      - network_dev
    labels:
      - com.multas.environment=dev

networks:
  network_dev:
    driver: bridge
