services:
  multas-api-dev:
    container_name: multas-api-dev
    build:
      context: ../../
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - sqlserverBack-dev
    env_file:
      - .env
    ports:
      - "5100:8080"
    networks:
      - multas_network
    labels:
      - com.multas.environment=dev

networks:
  multas_network:
    external: true
